# Generated by Django 3.2.13 on 2022-06-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "can_add_college_representative",
                        "Can add college representative",
                    ),
                    (
                        "can_view_college_representative",
                        "Can change college representative",
                    ),
                    (
                        "can_change_college_representative",
                        "Can view college representative",
                    ),
                    (
                        "can_delete_college_representative",
                        "Can delete college representative",
                    ),
                    (
                        "can_activate_college_representative",
                        "Can activate college representative",
                    ),
                    (
                        "can_deactivate_college_representative",
                        "Can deactivate college representative",
                    ),
                    (
                        "can_add_department_representative",
                        "Can add department representative",
                    ),
                    (
                        "can_view_department_representative",
                        "Can change department representative",
                    ),
                    (
                        "can_change_department_representative",
                        "Can view department representative",
                    ),
                    (
                        "can_delete_department_representative",
                        "Can delete department representative",
                    ),
                    (
                        "can_activate_department_representative",
                        "Can activate department representative",
                    ),
                    (
                        "can_deactivate_department_representative",
                        "Can deactivate department representative",
                    ),
                    ("can_add_staff_member", "Can add staff member"),
                    ("can_view_staff_member", "Can change staff member"),
                    ("can_change_staff_member", "Can view staff member"),
                    ("can_delete_staff_member", "Can delete staff member"),
                    ("can_activate_staff_member", "Can activate staff member"),
                    ("can_deactivate_staff_member", "Can deactivate staff member"),
                    ("can_add_store_officer", "Can add store officer"),
                    ("can_view_store_officer", "Can change store officer"),
                    ("can_change_store_officer", "Can view store officer"),
                    ("can_delete_store_officer", "Can delete store officer"),
                    ("can_activate_store_officer", "Can activate store officer"),
                    ("can_deactivate_store_officer", "Can deactivate store officer"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
