# Generated by Django 3.2.13 on 2022-06-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0004_auto_20220625_1830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="description"),
        ),
    ]
