# Generated by Django 3.2.13 on 2022-06-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0005_auto_20220625_1831"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="college",
            options={
                "permissions": [("can_change_status", "Can activate status")],
                "verbose_name": "college",
                "verbose_name_plural": "colleges",
            },
        ),
        migrations.AlterField(
            model_name="collegeuser",
            name="college",
            field=models.ForeignKey(
                limit_choices_to={"status": "active"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="auser.college",
                verbose_name="college",
            ),
        ),
        migrations.AlterField(
            model_name="collegeuser",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"status": "active"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staffs",
                to="auser.department",
                verbose_name="department",
            ),
        ),
    ]
