# Generated by Django 3.2.13 on 2022-06-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0006_auto_20220625_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegeuser",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"status": "active"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="auser.department",
                verbose_name="department",
            ),
        ),
    ]
