# Generated by Django 3.2.13 on 2022-05-19 13:45

import django.core.validators
import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models

import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="dead_stock_number",
            field=models.CharField(max_length=50, verbose_name="dead stock number"),
        ),
        migrations.AlterField(
            model_name="item",
            name="shelf",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="store",
                chained_model_field="store",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="store.shelf",
                verbose_name="shelf",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="supplier"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1900)],
                verbose_name="year",
            ),
        ),
        migrations.AlterField(
            model_name="shelf",
            name="shelf_id",
            field=models.CharField(
                default=store.models.uuid_hex,
                max_length=50,
                unique=True,
                verbose_name="shelf ID",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="value",
            field=models.CharField(max_length=255, verbose_name="value"),
        ),
    ]
