# Generated by Django 3.2.12 on 2022-05-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_service_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
