# Generated by Django 3.2.12 on 2022-07-09 21:49

import astu_inventory.apps.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'borrow history',
                'verbose_name_plural': 'borrow histories',
                'db_table': 'borrow_history',
            },
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(validators=[astu_inventory.apps.core.validators.validate_past], verbose_name='start date')),
                ('end_date', models.DateTimeField(validators=[astu_inventory.apps.core.validators.validate_past], verbose_name='end date')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Declined'), (3, 'Cancelled'), (4, 'Processing'), (5, 'Revoked'), (6, 'Completed'), (7, 'Returned')], default=0)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'borrow request',
                'verbose_name_plural': 'borrow requests',
                'db_table': 'borrow_request',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('borrow_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_reason', to='core.borrowrequest', verbose_name='borrow_request')),
            ],
            options={
                'verbose_name': 'reason',
                'verbose_name_plural': 'reasons',
                'db_table': 'reason',
            },
        ),
    ]
