# Generated by Django 3.2.12 on 2022-07-09 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_requests', to='inventory.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='user/requester'),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='borrow_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='core.borrowrequest', verbose_name='borrow requests'),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.item', verbose_name='item'),
        ),
    ]
