# Generated by Django 3.2.13 on 2022-06-30 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0008_alter_specification_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.SmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="start date")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Approved"),
                            (2, "Declined"),
                            (3, "Cancelled"),
                            (4, "Processing"),
                            (5, "Revoked"),
                            (6, "Processed"),
                        ],
                        default=0,
                    ),
                ),
                ("date_borrowed", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrow_requests",
                        to="inventory.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrow_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user/requester",
                    ),
                ),
            ],
            options={
                "verbose_name": "borrow request",
                "verbose_name_plural": "borrow requests",
                "db_table": "borrow_request",
            },
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reason",
                        to="core.borrowrequest",
                        verbose_name="request",
                    ),
                ),
            ],
            options={
                "verbose_name": "reason",
                "verbose_name_plural": "reasons",
                "db_table": "reason",
            },
        ),
        migrations.CreateModel(
            name="BorrowHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.SmallIntegerField(verbose_name="quantity")),
                (
                    "borrow_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="core.borrowrequest",
                        verbose_name="borrow requests",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "borrow history",
                "verbose_name_plural": "borrow histories",
                "db_table": "borrow_history",
            },
        ),
    ]
