# Generated by Django 3.2.13 on 2022-06-30 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrequest",
            name="quantity",
            field=models.SmallIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
