# Generated by Django 3.2.13 on 2022-06-30 14:50

import django.core.validators
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_borrowrequest_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowrequest",
            old_name="date_borrowed",
            new_name="date_requested",
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="end_date",
            field=models.DateTimeField(
                validators=[core.validators.validate_past], verbose_name="end date"
            ),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="quantity",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="start_date",
            field=models.DateTimeField(
                validators=[core.validators.validate_past], verbose_name="start date"
            ),
        ),
    ]
