# Generated by Django 3.2.13 on 2022-06-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220630_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='description',
            field=models.TextField(default='description', verbose_name='description'),
            preserve_default=False,
        ),
    ]
