# Generated by Django 3.2.13 on 2022-06-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_borrowrequest_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowrequest",
            name="description",
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="reason",
            field=models.TextField(default="", verbose_name="reason"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reason",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_reason",
                to="core.borrowrequest",
                verbose_name="request",
            ),
        ),
    ]
