# Generated by Django 3.2.13 on 2022-07-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20220630_1513"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reason",
            name="request",
        ),
        migrations.AddField(
            model_name="reason",
            name="borrow_request",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_reason",
                to="core.borrowrequest",
                verbose_name="borrow_request",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Approved"),
                    (2, "Declined"),
                    (3, "Cancelled"),
                    (4, "Processing"),
                    (5, "Revoked"),
                    (6, "Processed"),
                    (7, "Returned"),
                ],
                default=0,
            ),
        ),
    ]
