# Generated by Django 3.2.4 on 2022-07-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Help",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_name", models.CharField(max_length=150)),
                ("view_name", models.CharField(max_length=150)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Help",
                "verbose_name_plural": "Helps",
                "unique_together": {("app_name", "view_name")},
            },
        ),
    ]
