# Generated by Django 3.2.4 on 2022-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0002_alter_help_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="help",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
