# Generated by Django 3.2.12 on 2022-06-21 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('problem', models.TextField(verbose_name='problem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failurityreports', to='store.item', verbose_name='items')),
            ],
            options={
                'verbose_name': 'failurityreport',
                'verbose_name_plural': 'failurityreports',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='problem')),
                ('is_approved', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_declined', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenacerequests', to='maintenace.failurityreport', verbose_name='failurityreports')),
            ],
            options={
                'verbose_name': 'failurityreport',
                'verbose_name_plural': 'failurityreports',
            },
        ),
    ]
