# Generated by Django 4.0.4 on 2022-06-24 20:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auser', '0010_alter_schoolhead_options_alter_department_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('DSN', models.CharField(max_length=150)),
                ('year', models.DateTimeField(default=True)),
                ('supplier', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auser.department')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EPCE', 'EPCE')], max_length=100)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('consumable', 'consumable'), ('non-consumable', 'non-consumable')], max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('is_given', models.BooleanField(blank=True, null=True)),
                ('is_returned', models.BooleanField(blank=True, null=True)),
                ('is_other_dept', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='request.item', verbose_name='Item')),
            ],
            options={
                'ordering': ('-id',),
                'permissions': [('can_cancel_request', 'Can cancel request'), ('can_approve_request', 'Can approve request'), ('can_decline_request', 'Can decline request'), ('can_complete_request', 'Can complete request'), ('can_return_request', 'Can return request'), ('can_process_request', 'Can process request'), ('can_view_request_list', 'Can view request list'), ('can_view_request_detail', 'Can view request detail'), ('can_view_request_cancel', 'Can view request cancel'), ('can_view_request_approve', 'Can view request approve'), ('can_view_request_decline', 'Can view request decline'), ('can_view_request_complete', 'Can view request complete'), ('can_view_request_return', 'Can view request return'), ('can_view_processed_request', 'Can view processed request')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.store'),
        ),
    ]
