# Generated by Django 4.0.4 on 2022-06-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0010_alter_schoolhead_options_alter_department_school_and_more'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='auser.staffmember'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='request.item', verbose_name='Item'),
        ),
    ]
