# Generated by Django 4.0.4 on 2022-06-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0010_alter_schoolhead_options_alter_department_school_and_more'),
        ('request', '0002_request_requester_alter_request_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='auser.staffmember'),
        ),
    ]
