# Generated by Django 4.0.4 on 2022-06-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0010_alter_schoolhead_options_alter_department_school_and_more'),
        ('request', '0005_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='auser.department', verbose_name='department'),
            preserve_default=False,
        ),
    ]
