# Generated by Django 4.0.4 on 2022-06-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_request_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='requesting',
            new_name='is_other_dept',
        ),
    ]
