# Generated by Django 4.0.4 on 2022-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_remove_request_is_other_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requesting',
            field=models.BooleanField(default=True),
        ),
    ]
