# Generated by Django 4.0.4 on 2022-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_request_requesting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-id',), 'permissions': [('can_cancel_request', 'Can cancel request'), ('can_approve_request', 'Can approve request'), ('can_delete_request', 'Can delete request'), ('can_decline_request', 'Can decline request'), ('can_complete_request', 'Can complete request'), ('can_return_request', 'Can return request'), ('can_process_request', 'Can process request'), ('can_view_request_list', 'Can view request list'), ('can_view_request_detail', 'Can view request detail'), ('can_view_request_cancel', 'Can view request cancel'), ('can_view_request_approve', 'Can view request approve'), ('can_view_request_decline', 'Can view request decline'), ('can_view_request_complete', 'Can view request complete'), ('can_view_request_return', 'Can view request return'), ('can_view_processed_request', 'Can view processed request'), ('can_view_borrow_detail', 'Can view borrow detail')]},
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
