# Generated by Django 4.0.4 on 2022-06-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_alter_request_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='requesting',
            new_name='is_requesting',
        ),
    ]
