# Generated by Django 4.0.4 on 2022-06-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0012_rename_requesting_request_is_requesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_requesting',
            field=models.BooleanField(default=False),
        ),
    ]
