# Generated by Django 4.0.4 on 2022-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_alter_request_is_requesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_returned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
