# Generated by Django 4.0.4 on 2022-06-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_alter_request_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_requesting',
            field=models.BooleanField(default=True),
        ),
    ]
