# Generated by Django 3.2.12 on 2022-07-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0007_alter_user_options'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auser.department', verbose_name='department'),
        ),
    ]
