# Generated by Django 3.2.4 on 2022-07-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="availables",
            field=models.IntegerField(
                default=0, help_text="Currently number of available items.", verbose_name="Availables"
            ),
        ),
    ]
