# Generated by Django 3.2.4 on 2022-07-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_dead_stock_number'),
        ('inventory', '0004_product_availables'),
    ]

    operations = [
    ]
