# Generated by Django 3.2.12 on 2022-05-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='social_media_link',
        ),
        migrations.RemoveField(
            model_name='instructorsocialmedialink',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorsocialmedialink',
            name='social_media',
        ),
        migrations.DeleteModel(
            name='EducationBackground',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='InstructorSocialMediaLink',
        ),
    ]
