# Generated by Django 3.2.12 on 2022-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_deactivate_user', 'Can deactivate user'), ('can_activate_user', 'Can activate user'), ('can_view_schoolHead', 'Can view schoolHead'), ('can_change_schoolHead', 'Can change schoolHead'), ('can_add_schoolHead', 'Can add schoolHead'), ('can_delete_schoolHead', 'Can delete schoolHead'), ('can_change_user_permissions', 'Can change user permissions')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_schoolHead',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='schoolHead status'),
        ),
        migrations.DeleteModel(
            name='SchoolHead',
        ),
    ]
