# Generated by Django 3.2.12 on 2022-05-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0002_auto_20220510_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
