# Generated by Django 3.2.13 on 2022-06-28 01:26

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.category",
                verbose_name="category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="category",
                chained_model_field="category",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.subcategory",
                verbose_name="sub category",
            ),
            preserve_default=False,
        ),
    ]
