# Generated by Django 3.2.13 on 2022-06-28 02:25

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0001_initial"),
        ("inventory", "0003_auto_20220628_0126"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="college",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="auser.college",
                verbose_name="college",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="department",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="college",
                chained_model_field="college",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="auser.department",
                verbose_name="department",
            ),
            preserve_default=False,
        ),
    ]
