# Generated by Django 3.2.13 on 2022-06-28 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_auto_20220628_0225"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="measurment",
        ),
        migrations.AddField(
            model_name="product",
            name="measurment",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.measurment",
                verbose_name="measurement",
            ),
            preserve_default=False,
        ),
    ]
