# Generated by Django 3.2.13 on 2022-06-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_auto_20220628_0809"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="inventory.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="inventory.item",
                verbose_name="item",
            ),
        ),
    ]
