# Generated by Django 3.2.13 on 2022-06-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_auto_20220629_1801"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="specification",
            unique_together={
                ("product", "specification_type"),
                ("item", "specification_type"),
            },
        ),
    ]
