# Generated by Django 3.2.13 on 2022-06-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_specification_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.product",
                verbose_name="Product",
            ),
        ),
    ]
