# Generated by Django 3.2.13 on 2022-06-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_item_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.store",
                verbose_name="store",
            ),
        ),
    ]
