from .college import (ActivateCollegeView, AddCollegeView, CollegeDetailView,
                      DeactivateCollegeView, DeleteCollegeView,
                      ListCollegesView, UpdateCollegeView)
from .college_representative import (AddCollegeRepresentativeView,
                                     AddCollegeStaffMemberView,
                                     AssignCollegeRepresentativeView,
                                     CollegeRepresentativeActivateView,
                                     CollegeRepresentativeDeactivateView,
                                     CollegeRepresentativeDeleteView,
                                     CollegeRepresentativesListView,
                                     CollegeRepresentativeUpdateView,
                                     CollegeStaffMemberActivateView,
                                     CollegeStaffMemberDeactivateView,
                                     CollegeStaffMemberDeleteView,
                                     CollegeStaffMembersListView,
                                     CollegeStaffMemberUpdateView,
                                     RemoveFromCollegeRepresentativeView)
from .department import (ActivateDepartmentView, AddDepartmentView,
                         DeactivateDepartmentView, DeleteDepartmentView,
                         DepartmentDetailView, ListDepartmentsOfCollegeView,
                         UpdateDepartmentView)
from .department_representative import (AddDepartmentRepresentativeView,
                                        AddDepartmentStaffMemberView,
                                        DepartmentRepresentativeActivateView,
                                        DepartmentRepresentativeDeactivateView,
                                        DepartmentRepresentativeDeleteView,
                                        DepartmentRepresentativesListView,
                                        DepartmentRepresentativeUpdateView,
                                        DepartmentStaffMemberActivateView,
                                        DepartmentStaffMemberDeactivateView,
                                        DepartmentStaffMemberDeleteView,
                                        DepartmentStaffMembersListView,
                                        DepartmentStaffMemberUpdateView,
                                        RemoveFromDepartmentRepresentativeView)
from .officer import (CollegeLabAssistantsOfficersListView,
                      CollegeStoreOfficersListView,
                      DepartmentLabAssistantsOfficersListView,
                      DepartmentStoreOfficersListView)
from .user import (ActivateUserView, DeactivateUserView, DeleteUserView,
                   UpdateUserView)
from .view import DashboardView

__all__ = [
    "DepartmentLabAssistantsOfficersListView",
    "DepartmentStoreOfficersListView",
    "CollegeLabAssistantsOfficersListView",
    "CollegeStoreOfficersListView",
    "ActivateCollegeView",
    "AddCollegeView",
    "CollegeDetailView",
    "DeactivateCollegeView",
    "DeleteCollegeView",
    "ListCollegesView",
    "UpdateCollegeView",
    "AddCollegeRepresentativeView",
    "AssignCollegeRepresentativeView",
    "CollegeRepresentativeActivateView",
    "CollegeRepresentativeDeactivateView",
    "CollegeRepresentativeDeleteView",
    "CollegeRepresentativesListView",
    "CollegeRepresentativeUpdateView",
    "RemoveFromCollegeRepresentativeView",
    "ActivateDepartmentView",
    "AddDepartmentView",
    "DeactivateDepartmentView",
    "DeleteDepartmentView",
    "ListDepartmentsOfCollegeView",
    "UpdateDepartmentView",
    "AddDepartmentRepresentativeView",
    "ActivateUserView",
    "DeactivateUserView",
    "DeleteUserView",
    "UpdateUserView",
    "DashboardView",
    "CollegeStaffMemberActivateView",
    "CollegeStaffMemberDeactivateView",
    "DepartmentRepresentativeUpdateView",
    "DepartmentRepresentativeActivateView",
    "RemoveFromDepartmentRepresentativeView",
    "DepartmentRepresentativeDeactivateView",
    "DepartmentRepresentativeDeleteView",
    "AddCollegeStaffMemberView",
    "DepartmentStaffMemberUpdateView",
    "DepartmentStaffMemberActivateView",
    "DepartmentStaffMemberDeactivateView",
    "DepartmentStaffMemberDeleteView",
]
