# Generated by Django 3.2.4 on 2022-07-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_list_college_deans", "Can list college deans"),
                    ("can_add_college_dean", "Can add college dean"),
                    ("can_select_college_dean", "Can select college dean"),
                    ("can_change_college_dean", "Can change college dean"),
                    ("can_activate_college_dean", "Can activate college dean"),
                    ("can_deactivate_college_dean", "Can deactivate college dean"),
                    ("can_remove_college_dean", "Can remove college dean"),
                    ("can_delete_college_dean", "Can delete college dean"),
                    ("can_list_department_heads", "Can list department heads"),
                    ("can_add_department_head", "Can add department head"),
                    ("can_select_department_head", "Can select department head"),
                    ("can_change_department_head", "Can change department head"),
                    ("can_activate_department_head", "Can activate department head"),
                    ("can_deactivate_department_head", "Can deactivate department head"),
                    ("can_remove_department_head", "Can remove department head"),
                    ("can_delete_department_head", "Can delete department head"),
                    ("can_add_store_officer", "Can add store officer"),
                    ("can_list_store_officers", "Can list store officer"),
                    ("can_change_store_officer", "Can change store officer"),
                    ("can_activate_store_officer", "Can activate store officer"),
                    ("can_deactivate_store_officer", "Can deactivate store officer"),
                    ("can_remove_store_officer", "Can remove store officer"),
                    ("can_delete_store_officer", "Can delete store officer"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
