# Generated by Django 3.2.4 on 2022-07-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Active email address. Use organizational email (@astu.edu.et) if you have.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
