# Generated by Django 3.2.4 on 2022-07-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(help_text='Abbreviated name of the department. eg CSE, ECE, EPCE', max_length=10, unique=True, verbose_name='short name'),
        ),
    ]
