# Generated by Django 3.2.4 on 2022-07-05 11:51

import astu_inventory.apps.auser.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0003_alter_department_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_list_departments', 'Can list departments'), ('can_activate_department', 'Can acticate department')], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(help_text='Abbreviated name of the department. eg CSE, ECE, EPCE', max_length=10, unique=True, validators=[astu_inventory.apps.auser.validators.ShortNameValidator()], verbose_name='short name'),
        ),
    ]
