# Generated by Django 3.2.4 on 2022-07-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0004_auto_20220705_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_list_departments', 'Can list departments'), ('can_activate_department', 'Can acticate department'), ('can_deactivate_department', 'Can deacticate department')], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
