# Generated by Django 3.2.4 on 2022-07-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_list_college_deans", "Can list college deans"),
                    ("can_add_college_dean", "Can add college dean"),
                    ("can_select_college_dean", "Can select college dean"),
                    ("can_change_college_dean", "Can change college dean"),
                    ("can_activate_college_dean", "Can activate college dean"),
                    ("can_deactivate_college_dean", "Can deactivate college dean"),
                    ("can_remove_college_dean", "Can remove college dean"),
                    ("can_delete_college_dean", "Can delete college dean"),
                    ("can_list_department_heads", "Can list department heads"),
                    ("can_add_department_head", "Can add department head"),
                    ("can_select_department_head", "Can select department head"),
                    ("can_change_department_head", "Can change department head"),
                    ("can_activate_department_head", "Can activate department head"),
                    ("can_deactivate_department_head", "Can deactivate department head"),
                    ("can_remove_department_head", "Can remove department head"),
                    ("can_delete_department_head", "Can delete department head"),
                    ("can_add_store_officer", "Can add store officer"),
                    ("can_list_store_officers", "Can list store officer"),
                    ("can_change_store_officer", "Can change store officer"),
                    ("can_activate_store_officer", "Can activate store officer"),
                    ("can_deactivate_store_officer", "Can deactivate store officer"),
                    ("can_remove_store_officer", "Can remove store officer"),
                    ("can_delete_store_officer", "Can delete store officer"),
                    ("can_list_staff_members", "Can list staff member"),
                    ("can_add_staff_member", "Can add staff member"),
                    ("can_change_staff_member", "Can change staff member"),
                    ("can_activate_staff_member", "Can activate staff member"),
                    ("can_deactivate_staff_member", "Can deactivate staff member"),
                    ("can_delete_staff_member", "Can delete staff member"),
                    ("can_list_lab_assistant", "Can list lab assistant"),
                    ("can_add_lab_assistant", "Can add lab assistant"),
                    ("can_change_lab_assistant", "Can change lab assistant"),
                    ("can_activate_lab_assistant", "Can activate lab assistant"),
                    ("can_deactivate_lab_assistant", "Can deactivate lab assistant"),
                    ("can_remove_lab_assistant", "Can remove lab assistant"),
                    ("can_delete_lab_assistant", "Can delete lab assistant"),
                    ("can_view_detail_staff_member", "Can view detail staff memeber"),
                ],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
