# Generated by Django 3.2.4 on 2022-07-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0005_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_list_departments', 'Can list departments'), ('can_activate_department', 'Can activate department'), ('can_deactivate_department', 'Can deactivate department'), ('can_list_department_heads', 'Can list department heads')], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_list_college_deans', 'Can list college deans'), ('can_add_college_dean', 'Can add college dean'), ('can_select_college_dean', 'Can select college dean'), ('can_change_college_dean', 'Can change college dean'), ('can_activate_college_dean', 'Can activate college dean'), ('can_deactivate_college_dean', 'Can deactivate college dean'), ('can_remove_college_dean', 'Can remove college dean'), ('can_delete_college_dean', 'Can delete college dean')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
