# Generated by Django 3.2.4 on 2022-07-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auser", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="staff_id",
            field=models.CharField(
                error_messages={"unique": "A user with that staff ID already exists."},
                help_text="Unique staff ID number, that the college use to identify. ",
                max_length=250,
                unique=True,
                verbose_name="staff ID",
            ),
        ),
    ]
