# Generated by Django 3.2.4 on 2022-07-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0006_auto_20220705_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_list_college_deans', 'Can list college deans'), ('can_add_college_dean', 'Can add college dean'), ('can_select_college_dean', 'Can select college dean'), ('can_change_college_dean', 'Can change college dean'), ('can_activate_college_dean', 'Can activate college dean'), ('can_deactivate_college_dean', 'Can deactivate college dean'), ('can_remove_college_dean', 'Can remove college dean'), ('can_delete_college_dean', 'Can delete college dean'), ('can_list_department_heads', 'Can list department heads'), ('can_add_department_head', 'Can add department head'), ('can_select_department_head', 'Can select department head'), ('can_change_department_head', 'Can change department head'), ('can_activate_department_head', 'Can activate department head'), ('can_deactivate_department_head', 'Can deactivate department head'), ('can_remove_department_head', 'Can remove department head'), ('can_delete_department_head', 'Can delete department head')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
