# Generated by Django 3.2.12 on 2022-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0004_maintenancerequest_is_requeste'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_repaired',
            field=models.BooleanField(default=False),
        ),
    ]
