# Generated by Django 3.2.12 on 2022-06-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0006_auto_20220623_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_requeste',
        ),
    ]
