# Generated by Django 3.2.12 on 2022-06-23 18:17

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220519_1345'),
        ('maintenace', '0008_maintenancerequest_is_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name=[django.core.validators.MinValueValidator(0)])),
                ('problem', ckeditor.fields.RichTextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damagereport', to='store.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'damagereport',
                'verbose_name_plural': 'damagereports',
            },
        ),
    ]
