# Generated by Django 3.2.12 on 2022-06-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0016_alter_damagereport_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
