# Generated by Django 3.2.4 on 2022-07-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'permissions': (('can_list_available_product', 'Can list available products'), ('can_initiate_borrow_request', 'Can initiate borrow request'), ('can_list_active_borrow_request', 'Can list active borrow request'), ('can_view_active_borrow_request', 'Can view active borrow request'), ('can_approve_borrow_request', 'Can approve borrow request'), ('can_list_approved_borrow_request', 'Can list approved borrow request'), ('can_view_approved_borrow_request', 'Can view approved borrow request'), ('can_complete_borrow_request', 'Can complete borrow request'), ('can_revoke_borrow_request', 'Can revoke borrow request'), ('can_list_completed_borrow_request', 'Can list completed borrow request'), ('can_view_completed_borrow_request', 'Can view completed borrow request'), ('can_return_borrow_request', 'Can return borrow request'), ('can_list_borrow_request_history', 'Can list borrow request history')), 'verbose_name': 'borrow request', 'verbose_name_plural': 'borrow requests'},
        ),
        migrations.DeleteModel(
            name='BorrowHistory',
        ),
    ]
