# Generated by Django 3.2.13 on 2022-06-23 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="store_keepers",
        ),
        migrations.AddField(
            model_name="store",
            name="store_officers",
            field=models.ManyToManyField(
                limit_choices_to={"is_store_officer": True},
                related_name="stores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="store officer",
            ),
        ),
    ]
