# Generated by Django 3.2.12 on 2022-06-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DamageReport',
        ),
    ]
