# Generated by Django 3.2.12 on 2022-06-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0002_delete_damagereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'verbose_name': 'maintenance request', 'verbose_name_plural': 'maintenance requests'},
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenacerequests', to='maintenace.failurityreport', verbose_name='Item from failures'),
        ),
    ]
