# Generated by Django 3.2.12 on 2022-06-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0003_auto_20220622_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_requeste',
            field=models.BooleanField(default=True),
        ),
    ]
