# Generated by Django 3.2.12 on 2022-06-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0005_auto_20220623_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_damaged',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_repaired',
        ),
    ]
