# Generated by Django 3.2.12 on 2022-06-23 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0009_damagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='problem',
            field=models.TextField(blank=True, null=True, verbose_name='problem'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
