# Generated by Django 3.2.12 on 2022-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0010_auto_20220623_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
