# Generated by Django 3.2.12 on 2022-06-24 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0011_maintenancerequest_is_damaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='quantity',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
