# Generated by Django 3.2.12 on 2022-06-24 19:36

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0013_alter_damagereport_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='problem',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='quantity',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
