# Generated by Django 3.2.12 on 2022-06-24 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0014_auto_20220624_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='problem',
            field=ckeditor.fields.RichTextField(default=True),
        ),
    ]
