# Generated by Django 3.2.12 on 2022-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0015_alter_damagereport_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='problem',
            field=models.TextField(error_messages={'fill': 'You should specify the problem.'}),
        ),
    ]
