# Generated by Django 3.2.12 on 2022-06-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0017_auto_20220625_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_damaged',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
