# Generated by Django 3.2.12 on 2022-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0018_auto_20220625_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
