# Generated by Django 3.2.12 on 2022-06-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_quantity'),
        ('maintenace', '0020_maintenancerequest_decline_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='is_damaged',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='undermaintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenace.maintenancerequest', verbose_name='under maintenance'),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damagereport', to='store.item', verbose_name='item'),
        ),
    ]
