# Generated by Django 3.2.12 on 2022-06-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_quantity'),
        ('maintenace', '0021_auto_20220626_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='undermaintenance',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damagereport', to='store.item', verbose_name='item'),
        ),
    ]
