# Generated by Django 3.2.12 on 2022-06-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenace', '0023_maintenancerequest_is_repaired'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='undermaintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenace.maintenancerequest', verbose_name='under maintenance'),
        ),
    ]
