# Generated by Django 3.2.4 on 2022-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
