from django.urls import include, re_path

from inventory import views

app_name = "inventory"

urlpatterns = [
    re_path(
        r"^store/",
        include(
            [
                re_path(r"^$", views.ListStoresView.as_view(), name="stores_list"),
                re_path(
                    r"^add/$",
                    views.AddStoreView.as_view(),
                    name="add_store",
                ),
                re_path(
                    r"^(?P<pk>\d+)/",
                    include(
                        [
                            re_path(
                                r"^update/$",
                                views.UpdateStoreView.as_view(),
                                name="update_store",
                            ),
                            re_path(
                                r"^delete/$",
                                views.DeleteStoreView.as_view(),
                                name="delete_store",
                            ),
                            re_path(
                                r"^shelf/",
                                include(
                                    [
                                        re_path(
                                            r"^$",
                                            views.ListShelvesView.as_view(),
                                            name="shelves_list",
                                        ),
                                        re_path(
                                            r"^add/$",
                                            views.AddShelfView.as_view(),
                                            name="add_shelf",
                                        ),
                                        re_path(
                                            r"^(?P<shelf_id>[a-z0-9_\-]+)/",
                                            include(
                                                [
                                                    re_path(
                                                        r"^update/",
                                                        views.UpdateShelfView.as_view(),
                                                        name="update_shelf",
                                                    ),
                                                    re_path(
                                                        r"^delete/$",
                                                        views.DeleteShelfView.as_view(),
                                                        name="delete_shelf",
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    re_path(
        r"^specification/",
        include(
            [
                re_path(
                    r"^type/",
                    include(
                        [
                            re_path(
                                r"^$",
                                views.ListSpecificationTypesView.as_view(),
                                name="specification_types_list",
                            ),
                            re_path(
                                r"^add/$",
                                views.AddSpecificationTypeView.as_view(),
                                name="add_specification_type",
                            ),
                            re_path(
                                r"^(?P<pk>\d+)/",
                                include(
                                    [
                                        re_path(
                                            r"^update/$",
                                            views.UpdateSpecificationTypeView.as_view(),
                                            name="update_specification_type",
                                        ),
                                        re_path(
                                            r"^delete/$",
                                            views.DeleteSpecificationTypeView.as_view(),
                                            name="delete_specification_type",
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                )
            ]
        ),
    ),
    re_path(
        r"^category/",
        include(
            [
                re_path(
                    r"^$",
                    views.ListCategoriesView.as_view(),
                    name="categories_list",
                ),
                re_path(
                    r"^add/$", views.AddCategoryView.as_view(), name="add_category"
                ),
                re_path(
                    r"^(?P<slug>[-a-zA-Z0-9_]+)/",
                    include(
                        [
                            re_path(
                                r"^update/$",
                                views.UpdateCategoryView.as_view(),
                                name="update_category",
                            ),
                            re_path(
                                r"^delete/$",
                                views.DeleteCategoryView.as_view(),
                                name="delete_category",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    re_path(
        r"^subcategory/",
        include(
            [
                re_path(
                    r"^$",
                    views.ListSubCategoriesView.as_view(),
                    name="sub_categories_list",
                ),
                re_path(
                    r"^add/$",
                    views.AddSubCategoryView.as_view(),
                    name="add_sub_category",
                ),
                re_path(
                    r"^(?P<slug>[-a-zA-Z0-9_]+)/",
                    include(
                        [
                            re_path(
                                r"^update/$",
                                views.UpdateSubCategoryView.as_view(),
                                name="update_sub_category",
                            ),
                            re_path(
                                r"^delete/$",
                                views.DeleteSubCategoryView.as_view(),
                                name="delete_sub_category",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    re_path(
        r"^measurment/",
        include(
            [
                re_path(
                    r"^$",
                    views.ListMeasurmentsView.as_view(),
                    name="measurments_list",
                ),
                re_path(
                    r"^add/$", views.AddMeasurmentView.as_view(), name="add_measurment"
                ),
                re_path(
                    r"^(?P<pk>\d+)/",
                    include(
                        [
                            re_path(
                                r"^update/$",
                                views.UpdateMeasurmentView.as_view(),
                                name="update_measurment",
                            ),
                            re_path(
                                r"^delete/$",
                                views.DeleteMeasurmentView.as_view(),
                                name="delete_measurment",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
]
